version : 2.1
jobs:
  build:
    docker:
      - image: circleci/node:13-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm install mocha
      - run: npm i http-server
      - run:
          name: Run server in background
          command: './node_modules/http-server/bin/http-server'
          background: true
      - run:
          name: Run tests
          command: 'npm test'
