version : 2.1
jobs:
  build:
    docker:
      - image: circleci/node:16-browsers
    steps:
      - checkout
      - run: npm install
      - run:
          name: Run tests
          command: 'npm test'
